package com.tutorial.article.repository;

import com.tutorial.article.entity.BooksEntity;
import org.springframework.data.mongodb.repository.MongoRepository;

/**
 * Generated by MongoDB Relational Migrator
 * https://www.mongodb.com/products/relational-migrator
 * Collection: books
 * Language: Java
 * Template: Spring Data
 * Generated on 2025-01-22
 */
public interface BooksRepository extends MongoRepository<BooksEntity, String> {
}
