package com.tutorial.article.repository;

import com.tutorial.article.entity.ReviewsEntity;
import org.springframework.data.mongodb.repository.MongoRepository;

/**
 * Generated by MongoDB Relational Migrator
 * https://www.mongodb.com/products/relational-migrator
 * Collection: reviews
 * Language: Java
 * Template: Spring Data
 * Generated on 2025-01-22
 */
public interface ReviewsRepository extends MongoRepository<ReviewsEntity, String> {
}
